version: "3"
services:
  product-listener:
    build:
      context: .
    image: registry.wacodis.demo.52north.org/product-listener:1.1.1-SNAPSHOT
    network_mode: "host"
    environment:
      - product-listener.file-storage-directory=/wacodis_data/
    volumes:
      - /media/matthes/daten/wacodis_data/:/wacodis_data/
