server:
  port: 8082
spring:
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    config:
      url: http://localhost:8888
    stream:
      bindings:
        new-process-result:
          destination: wacodis.test.tools.finished
          binder: wacodis_rabbit
          group: jobStatusConsumers
        new-product:
          destination: wacodis.test.data.available
          binder: wacodis_rabbit
          content-type: application/json
      binders:
        wacodis_rabbit:
          type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
product-listener:
  wps-base-url: https://wacodis.demo.52north.org/wacodis-wps/service
  file-storage-directory: /media/matthes/daten/wacodis_data/
  dataAccessGetDataEnvelopeEndpoint: localhost:8081/dataAccess/dataenvelopes
  geoserver:
    enabled: true
    url: http://localhost:8080/geoserver
    service-type: WMS
    username: admin
    password: geoserver
  arcgis-image-server:
    enabled: false
    python-script-location: /home/dummy-ingestion.py
    url: arcgis.server.url/arcgis/admin
    service-type: ImageServer
  product-collection-mapping:
    - product-collection: EO:WACODIS:DAT:S2A_RAW # matches the resulting collection within the service backend
      product-type: sentinel-2_level-1c # matches the productCollection parameter from WacodisJobDefinition
    - product-collection: EO:WACODIS:DAT:NDVI
      product-type: ndvi