name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout WPS client lib
        uses: actions/checkout@v2
        with:
          repository: WaCoDiS/wps-client-lib
          ref: 1.0.8-wacodis
          path: wps-client-lib
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build dependencies
        run: mvn -B install --file ./wps-client-lib/pom.xml
      - name: Build
        run: mvn -B package --file pom.xml